# Hosts configuration for Docker Reverse Proxy
# This file defines the Docker hosts that RevP will monitor for containers.
#
# Each host can have its own SSH configuration including user, port, and key file.
# This provides much more flexibility than the legacy DOCKER_HOSTS environment variable.
#
# Format:
# hosts:
#   alias_name:
#     hostname: fully.qualified.domain.name
#     user: ssh_username
#     port: ssh_port (default: 22)
#     key_file: /path/to/ssh/private/key
#     description: "Human readable description"
#     enabled: true/false (default: true)
#     use_tailscale: true/false (default: true) - Use Tailscale IP if available
#
# defaults:
#   user: default_ssh_user
#   port: default_ssh_port
#   key_file: /path/to/default/key
#   enabled: default_enabled_state
#   use_tailscale: default_use_tailscale_state

# Default values applied to all hosts (can be overridden per host)
defaults:
  user: revp
  port: 22
  key_file: /home/app/.ssh/docker_monitor_key
  enabled: true

# Host definitions
hosts:
  switchboard:
    hostname: 192.168.86.32
    description: "Primary Docker Host (host.switchboard) - Main services and RevP controller"

  media-arr:
    hostname: 192.168.86.229
    description: "Media ARR Docker Host (host.media-arr) - Sonarr, Radarr, SABnzbd, Prowlarr"

  fabric:
    hostname: 192.168.86.145
    description: "Fabric Services Host (host.fabric) - Uptime monitoring and management tools"