# Hosts configuration for Docker Reverse Proxy
# This file defines the Docker hosts that RevP will monitor for containers.
#
# Each host can have its own SSH configuration including user, port, and key file.
# This provides much more flexibility than the legacy DOCKER_HOSTS environment variable.
#
# Format:
# hosts:
#   alias_name:
#     hostname: fully.qualified.domain.name
#     user: ssh_username
#     port: ssh_port (default: 22)
#     key_file: /path/to/ssh/private/key
#     description: "Human readable description"
#     enabled: true/false (default: true)
#
# defaults:
#   user: default_ssh_user
#   port: default_ssh_port
#   key_file: /path/to/default/key
#   enabled: default_enabled_state

# Default values applied to all hosts (can be overridden per host)
defaults:
  user: revp
  port: 22
  key_file: /root/.ssh/id_revp
  enabled: true

# Host definitions
hosts:
  switchboard:
    hostname: vm-switchboard.snadboy.com
    user: revp
    port: 22
    key_file: /root/.ssh/id_revp
    description: "Primary Docker Host (vm-switchboard) - Main services and RevP controller"
    enabled: true

  media-arr:
    hostname: vm-media-arr.snadboy.com
    user: revp
    port: 22
    key_file: /root/.ssh/id_revp
    description: "Media ARR Docker Host (vm-media-arr) - Sonarr, Radarr, SABnzbd, Prowlarr"
    enabled: true

  fabric:
    hostname: vm-fabric.snadboy.com
    user: revp
    port: 22
    key_file: /root/.ssh/id_revp
    description: "Fabric Services Host (vm-fabric) - Uptime monitoring and management tools"
    enabled: true