# Static routes configuration for RevP
# This file is automatically monitored for changes
# 
# WARNING: While you can edit this file manually, it's recommended to use
# the dashboard interface to prevent configuration conflicts and ensure
# proper validation.
#
# Format:
# static_routes:
#   - domain: example.com
#     backend_url: http://backend-server:8080
#     backend_path: /
#     force_ssl: true
#     support_websocket: false

static_routes:
- domain: api7.test.local
  backend_url: http://localhost:8000
  backend_path: /
  force_ssl: false
  support_websocket: false
- domain: admin.test.local
  backend_url: https://192.168.1.101:8443
  backend_path: /dashboard
  force_ssl: true
  support_websocket: true
- domain: monitoring.test.local
  backend_url: http://monitoring-server:9090
  backend_path: /
  force_ssl: true
  support_websocket: false
- domain: newroute.test.local
  backend_url: http://192.168.1.200:5000
  backend_path: /api
  force_ssl: true
  support_websocket: true
- domain: filewatch.test.local
  backend_url: http://192.168.1.201:6000
  backend_path: /
  force_ssl: false
  support_websocket: false
