# Static routes configuration for RevP
# This file is automatically monitored for changes
# 
# WARNING: While you can edit this file manually, it's recommended to use
# the dashboard interface to prevent configuration conflicts and ensure
# proper validation.
#
# Format:
# static_routes:
#   - domain: example.com
#     backend_url: http://backend-server:8080
#     backend_path: /
#     force_ssl: true
#     support_websocket: false
#     tls_insecure_skip_verify: false  # Use only for self-signed certs (home servers)

static_routes:
- domain: colossus.snadboy.com
  backend_url: https://colossus:8006
  backend_path: /
  force_ssl: true
  support_websocket: true
  tls_insecure_skip_verify: true
- domain: guardian.snadboy.com
  backend_url: https://guardian:8006
  backend_path: /
  force_ssl: true
  support_websocket: true
  tls_insecure_skip_verify: true
- domain: pihole.snadboy.com
  backend_url: https://dns:443
  backend_path: /
  force_ssl: true
  support_websocket: false
  tls_insecure_skip_verify: true
- domain: unifi.snadboy.com
  backend_url: http://192.168.86.1:80
  backend_path: /
  force_ssl: false
  support_websocket: false
  tls_insecure_skip_verify: false
- domain: think-plex.snadboy.com
  backend_url: http://think-plex:32400
  backend_path: /
  force_ssl: true
  support_websocket: false
  tls_insecure_skip_verify: false
- domain: plex.snadboy.com
  backend_url: https://plex:32400
  backend_path: /
  force_ssl: true
  support_websocket: false
  tls_insecure_skip_verify: false
