# Static routes configuration for RevP
# This file is automatically monitored for changes
# 
# WARNING: While you can edit this file manually, it's recommended to use
# the dashboard interface to prevent configuration conflicts and ensure
# proper validation.
#
# Format:
# static_routes:
#   - domain: example.com
#     backend_url: http://backend-server:8080
#     backend_path: /
#     force_ssl: true
#     support_websocket: false

static_routes:
- domain: colossus.snadboy.com
  backend_url: https://192.168.86.102:8006
  backend_path: /
  force_ssl: false
  support_websocket: true
  tls_insecure_skip_verify: true
- domain: guardian.snadboy.com
  backend_url: https://192.168.86.96:8006
  backend_path: /
  force_ssl: true
  support_websocket: true
  tls_insecure_skip_verify: true
